name: Reusable Workflow
on:
  workflow_call:
    inputs:
      app-artifact:
        type: string
        default: dist
        description: The artifact to be downloaded injected from the caller workflow
        required: false

jobs:
  Get-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v3
            with: ${{ inputs.app-artifact }}
      - name: List files
        run: ls -l
