name: App Matrix Pipeline
on:
  workflow_dispatch:
  push:
jobs:
  test:
    strategy:
      matrix:
        op-systems: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.op-systems }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
